Models/Calculadora.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace mvc_lab.Models
{
    public class Calculadora
    {
        public int Operador1 { get; set; }

        public int Operador2 { get; set; }

        public String Accion { get; set; }

        [Display(Name="Output")]
        public int Respuesta { get; set; }
    }
}

Models/Contacto.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace mvc_lab.Models
{
    public class Contacto
    {

        [Required]
        [Display(Name="Name")]
        public String Nombre{ get; set; }

        [Required]
        [Display(Name="LastName")]
        public String Apellido{ get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name="Email")]
        public String Email{ get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name="Phone")]
        public int Telefono{ get; set; }

        [Required]
        [Display(Name="Subject")]
        public String Titulo{ get; set; }

        [Required]
        [Display(Name="Message")]
        public String Mensaje{ get; set; }

        [Display(Name="Output")]
        public String Respuesta { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace mvc_lab.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Estudiante.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace mvc_lab.Models{
    public class Estudiante{

        [Required]
        public String Name{ get; set; }

        [Required]
        public String Last_name{ get; set; }

        [Required]
        public String Subject{ get; set; }

        [Display(Name="Answer")]
        public String Answer{ get; set; }
    }
}

Controllers/CalculadoraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_lab.Models;

namespace mvc_lab.Controllers
{
    public class CalculadoraController : Controller
    {
        private readonly ILogger<CalculadoraController> _logger;

        public CalculadoraController(ILogger<CalculadoraController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Calcular(Calculadora calc){
            if(calc.Accion=="+"){
                calc.Respuesta= calc.Operador1 + calc.Operador2;
            }else if(calc.Accion=="-"){
                calc.Respuesta= calc.Operador1 - calc.Operador2;
            }else if(calc.Accion=="*"){
                calc.Respuesta= calc.Operador1 * calc.Operador2;
            }else{
                calc.Respuesta= calc.Operador1 / calc.Operador2;
            }

            return View("Index",calc);
        }
    }
}

Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_lab.Models;

namespace mvc_lab.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ILogger<ContactoController> _logger;

        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(Contacto contacto){
            if(ModelState.IsValid){
                contacto.Respuesta="Gracias por su elección";
            }
            return View("Index",contacto);
        }
    }
}

Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_lab.Models;

namespace mvc_lab.Controllers{
    public class EstudianteController : Controller{

        private readonly ILogger<EstudianteController> _logger;

        public EstudianteController(ILogger<EstudianteController> logger){

            _logger=logger;
        }

        public IActionResult Index(){
            return View();
        }

        [HttpPost]
        public IActionResult Almacenar(Estudiante estudiante){
            if(ModelState.IsValid){
                estudiante.Answer="Registro de Base de Datos (*)";
            }

            return View("Index",estudiante);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_lab.Models;

namespace mvc_lab.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calculadora/Index.cshtml
@model mvc_lab.Models.Calculadora

@{
    ViewData["Title"] = "Calculadora Page";
}

<div class="text-center">
    <h1 class="display-4">Calculadora</h1>
    <form asp-controller="Calculadora" asp-action="Calcular">
        <label>Operador 1</label>
        <input asp-for="Operador1"/>
        <br>
        <label>Operador 2</label>
        <input asp-for="Operador2"/>
        <br>
        <label>Accion</label>
        <select asp-for="Accion">
            <option value="+">Suma</option>
            <option value="-">Resta</option>
            <option value="*">Multiplicación</option>
            <option value="/">División</option>
        </select>
        <br>
        <input type="submit" value="Calcular"/>
    </form>

    <td>@Html.DisplayNameFor(Model=> Model.Respuesta)</td>
    <td>@Html.DisplayTextFor(Model=> Model.Respuesta)</td>
</div>

Views/Contacto/Index.cshtml
@model mvc_lab.Models.Contacto

@{
    ViewData["Title"] = "Contacto";
}

<div class="row">  
    <div class="col-md-4">
        <h1 class="display-4">Contacto</h1>
        <form asp-controller="Contacto" asp-action="Registrar">
            <div asp-asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control"/>
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control"/>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control"/>
            </div>

            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control"/>
            </div>

            <div class="form-group">
                <label asp-for="Mensaje" class="control-label"></label>
                <textarea asp-for="Mensaje" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <button type="submit" value="Registrar" class="btn-btn-primary">Registrar</button>
            </div>
        </form>

        <td>@Html.DisplayTextFor(Model=> Model.Respuesta)</td>
    </div>
</div>

Views/Estudiante/Index.cshtml
@model mvc_lab.Models.Estudiante

@{
    ViewData["Title"] = "Estudiante";
}

<div class="row">  
    <div class="col-md-4">
        <h1 class="display-4">Estudiante</h1>
        <form asp-controller="Estudiante" asp-action="Almacenar">
            <div asp-asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" name="name"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Last_name" class="control-label"></label>
                <input asp-for="Last_name" class="form-control" name="last_name"/>
                <span asp-validation-for="Last_name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <select class="form-control" asp-for="Subject" name="subject">
                    <option value="Matematica">Matematica</option>
                    <option value="Historia">Historia</option>
                    <option value="Lenguaje">Lenguaje</option>
                    <option value="Geografia">Geografia</option>
                </select>
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Almacenar"/>
            </div>
        </form>

        <td>@Html.DisplayTextFor(Model=> Model.Answer)</td>

    </div>
   
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Share/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_lab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc_lab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiante" asp-action="Index">Estudiante</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - mvc_lab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>